spring:
  profiles:
    active:
      - local
  devtools:
    restart:
      enabled: false
#  jackson:
#    property-naming-strategy: LOWER_CAMEL_CASE

upbit-config:
  base-url: https://api.upbit.com