spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: a
    password: a
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 60 # minutes

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: market-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

korea-trade-open-api:
  app-key: a
  app-secret: a
  real-domain: https://openapi.koreainvestment.com:9443
  real-websocket-domain: ws://ops.koreainvestment.com:21000
  mock-domain: https://openapivts.koreainvestment.com:29443
  mock-websocket-domain: ws://ops.koreainvestment.com:31000